package com.kodilla.exception.test;

public class ExceptionHandling {

    public static void main(String[] args) {
//        SecondChallenge secondChallenge = new SecondChallenge();
//
//        try {
//            secondChallenge.probablyIWillThrowException();
//        } catch(Exception e) {
//            System.out.println("Error" + e);
//        } finally {
//            System.out.println("finally :)");
//        }
    }
}
